### ISSUE TITLE
Feedback for "Role Collections"

### ISSUE THREAD

**Issue by freetimecoder3** [SAP-docs/cloud-alm-setup-admin-guide#9]
https://help.sap.com/docs/cloud-alm/setup-administration/role-collections?locale=en-US

Hi,
Am having some major queries with the terminology at this page.  Have left comments on the page.
Kindly update to clarify.

BR,
Ganesh S

**Comment by laura-branitsch** [comment]
Hi @freetimecoder3, thank you for your feedback! We’ll look into it and come back to you as soon as possible.

**Comment by laura-branitsch** [comment]
Hi @freetimecoder3,

Let me address your comments one by one:
 
1) **Terminology**:
You're right that the typical hierarchy is role collection -> role -> role template. However, the simple answer to most of your questions is that there's a 1:1 relationship between role templates and role collections in SAP Cloud ALM. 

2) **Bundling several role collections**
In the underlying SAP BTP subaccount, there are both roles and role collections. 
Since SAP Cloud ALM role collections correspond 1:1 to role templates, there is no way to break down existing role collections into smaller components. However, you have the option of bundling several SAP Cloud ALM role collections together.

3) **Role title** 
In the _User Management_ app in SAP Cloud ALM, we speak of "roles" rather than "role collections". This is what the column header refers to. I've extended this label a little bit to make this clearer.

4) **Custom or predefined role collections** 
It's option a). Every application role in SAP Cloud ALM represents a role collection. That means that for each role, there will be a role collection on SAP BTP. They are predefined and ready to use, you just have to select them. 

To make all of this a little more transparent, I will add a short explanation about roles and role collections to this document. This should remove any ambiguity in the future.

Please let me know if you have further questions.

Best regards,
Laura

**Comment by freetimecoder3** [comment]
> Hi @freetimecoder3,
> 
> Let me address your comments one by one:
> 
> 1. **Terminology**:
>    You're right that the typical hierarchy is role collection -> role -> role template. However, the simple answer to most of your questions is that there's a 1:1 relationship between role templates and role collections in SAP Cloud ALM.
> 2. **Bundling several role collections**
>    In the underlying SAP BTP subaccount, there are both roles and role collections.
>    Since SAP Cloud ALM role collections correspond 1:1 to role templates, there is no way to break down existing role collections into smaller components. However, you have the option of bundling several SAP Cloud ALM role collections together.
> 3. **Role title**
>    In the _User Management_ app in SAP Cloud ALM, we speak of "roles" rather than "role collections". This is what the column header refers to. I've extended this label a little bit to make this clearer.
> 4. **Custom or predefined role collections**
>    It's option a). Every application role in SAP Cloud ALM represents a role collection. That means that for each role, there will be a role collection on SAP BTP. They are predefined and ready to use, you just have to select them.
> 
> To make all of this a little more transparent, I will add a short explanation about roles and role collections to this document. This should remove any ambiguity in the future.
> 
> Please let me know if you have further questions.
> 
> Best regards, Laura


Hi Laura,
Thanks for the detailed reverts.  I look forward to your additional comments to the document.

If i may suggest, please include the relationship between ALM Objects to the underlying BTP Object.  E.g., ALM Roles are available/mapped as Role Collection in BTP SubAccount, like that.

BR,
Banesh S

**Comment by laura-branitsch** [comment]
Will do. Thank you for your remarks, @freetimecoder3!
